services:
  mongo:
    image: mongo:latest
    container_name: BookingDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./database/mongodb/:/data/db
    ports:
      - "${MONGO_PORT}:27017"
